version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn django_sec.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 1300:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/staticfiles
volumes:
  postgres_data:
  static_volume:
